// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUv4faCCVSibmxjx54Ts9nxW_YiBJmq2M',
    appId: '1:990619914133:web:27b40e3ea15329a965f09c',
    messagingSenderId: '990619914133',
    projectId: 'delivery-app-dc02c',
    authDomain: 'delivery-app-dc02c.firebaseapp.com',
    storageBucket: 'delivery-app-dc02c.appspot.com',
    measurementId: 'G-GXDZ6J5TF2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0thNtn9jgl0ihO-9HkOEHdBRAvg2AjfY',
    appId: '1:990619914133:android:4f0bdcadf32100ad65f09c',
    messagingSenderId: '990619914133',
    projectId: 'delivery-app-dc02c',
    storageBucket: 'delivery-app-dc02c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARZbKimuUyKHFV8t3kLtqGS3LCnysBpuA',
    appId: '1:990619914133:ios:d6f4ce9ccfea69ef65f09c',
    messagingSenderId: '990619914133',
    projectId: 'delivery-app-dc02c',
    storageBucket: 'delivery-app-dc02c.appspot.com',
    iosBundleId: 'com.example.deliveryApp',
  );
}
